--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/Theslowaja-pm-pl/minions
build-by-default: true
branches:
- main
projects:
  minions:
    path: ""
    libs:
      - src: muqsit/invMenu/InvMenu
        version: ^4.4.0
...
